### ISSUE TITLE
Workshop6 Scrum report 7/30

### ISSUE THREAD

**Issue by Nick-zhen** [terryzhan0211/GO-TRAVEL#101]

**Comment by DKIV9570** [comment]
Jin Niu CSID: b3w2b

(1) what you’ve worked on in the previous two weeks
a) Restructure cities, now it is separate from posts, this could make a bunch of options faster and make more sense. 
b) Backend work of new feature search, which make users be able to navigate to any city with a post by their cityName. Also took part in connecting the backend with the frontend.
c)  Backend work for User's new feature change password. Users can change their passwords now.
d)  Debugging

(2)What were any major issues/challenges you ran into?
a) Asynchronous nature of data acquisition gave us several problems, mainly about rendering the page before getting the data needed. We fixed that by monitoring the state of pending and fulfilled.

(3) What do you plan to work on for this coming iteration (2 weeks)?
a) Apply state monitoring on more operations, try to use a spinner
b) Debug all loose ends and make sure our project runs smoothly
c) improve the user page with stuff like editing info pictures and background pictures. Maybe also more information if the time is plenty.

**Comment by shhhawn9** [comment]
Shawn Gu CSID: z1h7k

(1) what you’ve worked on in the previous two weeks
a) reconstruct the backend and wire the front end with URL params.
b) add share function to post detail page
c) debugging backend and front end
d) improve CSS

(2)What were any major issues/challenges you ran into?
a) the asynchronous between fetching data and rendering.

(3) What do you plan to work on for this coming iteration (2 weeks)?
a) use the state of dispatching to control rendering
b) add like count to post detail page
c) fix font issue

**Comment by Nick-zhen** [comment]
Kaining Zheng CSID: g4b6z
(1) what you’ve worked on in the previous two weeks
a) refractory code. Separate Posts from Cities.
b) implemented get, add, and delete a post in server and wire it between server and frontend.
c) debug the backend

(2)What were any major issues/challenges you ran into?
a) the redux state sometimes changes localStorage, but sometimes doesn't. I still don't figure out how it comes.

(3) What do you plan to work on for this coming iteration (2 weeks)?
a) add like count to post
b) fix the rendering old state bug
c). add comment feature if have time

**Comment by terryzhan0211** [comment]
Xinye Zhan CSID: v0y2b
(1) what you’ve worked on in the previous two weeks
a) refractory code. 
b) implement a search component to navigate post lists with city names
c) introduce onKeyPress and onKeyclick properties to frontend to improve user experience

(2)What were any major issues/challenges you ran into?
a) The navigate page feature doesn't work fine even if we get the correct URL. It is a bug with async problems.

(3) What do you plan to work on for this coming iteration (2 weeks)?
a) fix like post number rendering feature
b) add comment feature on the post detail page if have time. this requires change of MongoDB collection and we need to fix
